name: ms_smart_tools_monorepo
repository: https://github.com/user/ms_smart_tools

packages:
  - .
  - apps/*
  - packages/core/*
  - packages/features/*

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    exec: flutter analyze
    description: Run flutter analyze in all packages.

  test:
    exec: flutter test
    description: Run flutter test in all packages.

  build:apk-split:
    exec: flutter build apk --split-per-abi
    packageFilters:
      dirExists: android
    description: Build split-per-abi release APKs for all applications.

  build:apk:
    exec: flutter build apk --release
    packageFilters:
      dirExists: android
    description: Build release APKs for all applications.
